print("Student Name:")
Student_name=input()
print("Rollno:")
Roll_no=input()
print("Tamil:")
Tamil=int(input())
print("English:")
English=int(input())
print("Maths:")
Maths=int(input())
print("Science:")
science=int(input())
print("Social:")
social=int(input())
print("Total Marks:")
Total=input(Tamil+English+Maths+science+social)